apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secret
  namespace: cicd
type: Opaque
stringData:
  # Replace these placeholder values with real secrets before applying
  DATABASE_URL: "postgres://user:password@db.example.com:5432/dbname"
  JWT_SECRET: "REPLACE_WITH_A_STRONG_SECRET"
  DUCKDNS_TOKEN: "REPLACE_WITH_DUCKDNS_TOKEN_IF_USING_DUCKDNS"
